import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout from "@/components/Layout/Layout";
import { useState } from "react";
import LayoutPanel from "@/components/LayoutPanel/LayoutPanel";
import { IconHome2, IconListDetails, IconSettings } from "@tabler/icons-react";
import { Navigation } from "@/components/DoubleNavBar/DoubleNavBar";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const navigations: Navigation[] = [
  { icon: IconHome2, label: "Home" },
  { icon: IconListDetails, label: "List" },
  { icon: IconSettings, label: "Settings" },
];

const DynamicHome = dynamic(() => import("@/components/Home/Home"), {
  ssr: false,
});

export default function Index() {
  const [label, setLabel] = useState<string>("Home");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        label={label}
        navigations={navigations}
        onNavigationChange={setLabel}
      >
        <LayoutPanel label="Home">
          <DynamicHome />
        </LayoutPanel>
      </Layout>
    </>
  );
}
